version: '2'
services:
  tracker:
    container_name: tracker
    image: massinger/fastdfs-docker
    command: tracker
    network_mode: host
    volumes:   
      - fdfs-tracker:/var/fdfs    
  storage:
    container_name: storage
    image: massinger/fastdfs-docker
    command: storage
    network_mode: host  
    links:
      - tracker:tracker
    environment:
      - TRACKER_SERVER=tracker:22122
    volumes: 
      - fdfs-storage:/var/fdfs
  # storage1:
  #   container_name: storage1
  #   image: luhuiguo/fastdfs
  #   command: storage
  #   network_mode: host  
  #   environment:
  #     - TRACKER_SERVER=10.1.5.85:22122
  #   volumes: 
  #     - /var/fdfs/storage1:/var/fdfs
  #  storage2:
  #   container_name: storage2
  #   image: luhuiguo/fastdfs
  #   command: storage
  #   network_mode: host  
  #   environment:
  #     - TRACKER_SERVER=10.1.5.85:22122
  #     - GROUP_NAME=group2
  #     - PORT=24000
  #   volumes: 
  #     - /var/fdfs/storage2:/var/fdfs           
                    
